apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-loki-pv
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: loki
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.102
    path: /data/nfs-shared/logging/loki
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-loki-pvc
  namespace: logging
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: logging-loki-pv
